### ISSUE TITLE
Support for overriding `ToString`

### ISSUE THREAD

**Issue by halgari** [erri120/TransparentValueObjects#20]
I often want a non-standard printer for my wrapped objects. Mostly so I can tell a difference between a integer and some other form of it. For example I may want `Color<uint>` to be displayed as `#FF00122` instead of `4278194466`. 

Right now I can't override ToString since the code generation does it already.

**Comment by erri120** [comment]
This is already supported, but it's a bit weird to use. You just write a normal `ToString` method and once the source generator runs again, it will find the existing method and then it won't implement it's own version.

https://github.com/erri120/TransparentValueObjects/blob/main/tests/TransparentValueObjects.Tests/SourceOutput/ExistingMethod.cs

https://github.com/erri120/TransparentValueObjects/blob/main/tests/TransparentValueObjects.Tests/SourceOutput/ExistingMethod.Test_WithExistingMethod.verified.cs
